### PR TITLE
Get credentials from Moonshot Identity Selector if it's available. Closes #18.

### LINKED ISSUE #18: Pull in updated credential management from Moonshot's mech_eap
Storing username/password in ~/.gss_eap_id is not acceptable for production use. Moonshot has improved credential management code that mech_saml_ec should pull in and use.

### PR DESCRIPTION
**Pull request by nawatts**

### CODE REVIEW

**Comment by nawatts** [comment]
@jbasney @spaetow would you please look this over?

**Comment by jgemmill** [comment]
huzzah!!

On Wed, Jun 8, 2016 at 10:53 AM, Nick Watts <notifications@github.com>
wrote:

> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/fedushare/mech_saml_ec/pull/19
> Commit Summary
>
>    - Get credentials from Moonshot Identity Selector if it's available.
>    Closes #18.
>
> File Changes
>
>    - *M* acinclude.m4
>    <https://github.com/fedushare/mech_saml_ec/pull/19/files#diff-0> (34)
>    - *M* build-aux/compile
>    <https://github.com/fedushare/mech_saml_ec/pull/19/files#diff-1> (232)
>    - *M* configure.ac
>    <https://github.com/fedushare/mech_saml_ec/pull/19/files#diff-2> (1)
>    - *M* mech_saml_ec/Makefile.am
>    <https://github.com/fedushare/mech_saml_ec/pull/19/files#diff-3> (9)
>    - *M* mech_saml_ec/util.h
>    <https://github.com/fedushare/mech_saml_ec/pull/19/files#diff-4> (2)
>    - *A* mech_saml_ec/util_moonshot.c
>    <https://github.com/fedushare/mech_saml_ec/pull/19/files#diff-5> (283)
>
> Patch Links:
>
>    - https://github.com/fedushare/mech_saml_ec/pull/19.patch
>    - https://github.com/fedushare/mech_saml_ec/pull/19.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/fedushare/mech_saml_ec/pull/19>, or mute the thread
> <https://github.com/notifications/unsubscribe/AOddYV-oHhnqNdjKeErROgi3i60nAG-Lks5qJtdngaJpZM4IxDHR>
> .
>



-- 
- Jill

**Comment by jbasney** [comment]
@nawatts Where are the functions in mech_saml_ec/util_moonshot.c called from? Checking the diffs in this pull request I see the new libMoonshot functions being defined but not called.

**Comment by nawatts** [comment]
They were already present (#ifdef'd out) in util_cred.c lines [498](https://github.com/fedushare/mech_saml_ec/blob/moonshot-credentials/mech_saml_ec/util_cred.c#L498) and [846](https://github.com/fedushare/mech_saml_ec/blob/moonshot-credentials/mech_saml_ec/util_cred.c#L846)

**Comment by jbasney** [comment]
@nawatts Looks great to me!

**Pull request merged**
